### ISSUE TITLE
Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by javaHelper** [springhow/spring-boot-security-password-encoder#1]
I am getting error mentioned here - https://stackoverflow.com/questions/67692375/caused-by-java-sql-sqlsyntaxerrorexception-specified-key-was-too-long-max-key

Any quick help? DB using is MySQL 8+.

**Comment by raja-anbazhagan** [comment]
Looks like you are adding a unique constraint on the `username`  column. And the problem here is that this column length is 500 characters. But because you may be using UTF-8, each character would take 3 bytes. So the total length of the column is 1500. And in MySQL, you can't have an index with a column length of more than 1000 bytes.

So to answer your question, reduce the number of chars in your column. Or increase the byte limit for MySQL indexes(usually a bad idea as this would cause performance issue.).
